name: CI/CD

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 21

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build app
        run: mvn -B clean package --file pom.xml